<?php
declare(strict_types=1);
namespace Extcode\CartPdf\EventListener\ProcessOrderCreate;

/*
 * This file is part of the package extcode/cart-pdf.
 *
 * For the full copyright and license information, please read the
 * LICENSE file that was distributed with this source code.
 */

use Extcode\Cart\Domain\Repository\Order\ItemRepository as OrderItemRepository;
use Extcode\Cart\Event\ProcessOrderCreateEvent;
use Extcode\Cart\Utility\OrderUtility;
use Extcode\CartPdf\Service\PdfService;
use TYPO3\CMS\Extbase\Persistence\Generic\PersistenceManager;

class DocumentRenderer
{
    /**
     * @var PersistenceManager
     */
    protected $persistenceManager;

    /**
     * @var OrderItemRepository
     */
    protected $orderItemRepository;

    /**
     * @var OrderUtility
     */
    protected $orderUtility;

    /**
     * @var PdfService
     */
    protected $pdfService;

    /**
     * @var array
     */
    protected $settings = [];

    public function __construct(
        PersistenceManager $persistenceManager,
        OrderItemRepository $orderItemRepository,
        OrderUtility $orderUtility,
        PdfService $pdfService
    ) {
        $this->persistenceManager = $persistenceManager;
        $this->orderItemRepository = $orderItemRepository;
        $this->orderUtility = $orderUtility;
        $this->pdfService = $pdfService;
    }

    public function __invoke(ProcessOrderCreateEvent $event): void
    {
        $orderItem = $event->getOrderItem();
        $this->settings = $event->getSettings();

        if ($this->settings['autoGenerateDocuments']) {
            foreach ($this->settings['autoGenerateDocuments'] as $documentType => $documentData) {
                $getterForNumber = 'get' . ucfirst($documentType) . 'Number';
                $setterForNumber = 'set' . ucfirst($documentType) . 'Number';
                $setterForDate = 'set' . ucfirst($documentType) . 'Date';

                if (!$orderItem->$getterForNumber()) {
                    $documentNumber = $this->orderUtility->getNumber($this->settings, $documentType);

                    $orderItem->$setterForNumber($documentNumber);
                    $orderItem->$setterForDate(new \DateTime());
                }

                $this->pdfService->createPdf($orderItem, $documentType);
            }

            $this->orderItemRepository->update($orderItem);
            $this->persistenceManager->persistAll();
        }
    }
}
