<?php

declare(strict_types=1);

/*
 * (c) 2025 rc design visual concepts (rc-design.at)
 * _________________________________________________
 * The TYPO3 project - inspiring people to share!
 * _________________________________________________
 */

namespace Extcode\CartPdf\EventListener\ProcessOrderCreate;

use DateTime;
use Exception;
use Extcode\Cart\Domain\Repository\Order\ItemRepository as OrderItemRepository;
use Extcode\Cart\Event\ProcessOrderCreateEvent;
use Extcode\CartPdf\Service\PdfService;
use TYPO3\CMS\Extbase\Persistence\Generic\PersistenceManager;

class DocumentRenderer
{
    public function __construct(
        protected PersistenceManager $persistenceManager,
        protected OrderItemRepository $orderItemRepository,
        protected PdfService $pdfService,
        protected array $options = []
    ) {}

    public function __invoke(ProcessOrderCreateEvent $event): void
    {
        $orderItem = $event->getOrderItem();
        $settings = $event->getSettings();

        // Bestimme, welche Dokumente generiert werden sollen
        $generateDocuments = (array)($settings['autoGenerateDocuments'] ?? []);
        if (isset($this->options['autoGenerateDocuments']) && is_array($this->options['autoGenerateDocuments'])) {
            $generateDocuments = array_merge($generateDocuments, $this->options['autoGenerateDocuments']);
        }

        if (empty($generateDocuments)) {
            return;
        }

        $hasChanges = false;

        foreach ($generateDocuments as $documentType => $shouldGenerate) {
            if (!(bool)$shouldGenerate) {
                continue;
            }

            // Nur Order und Invoice unterstützen
            if (!in_array($documentType, ['order', 'invoice', 'delivery'])) {
                continue;
            }

            $getterNumber = 'get' . ucfirst($documentType) . 'Number';
            $getterDate = 'get' . ucfirst($documentType) . 'Date';
            $setterDate = 'set' . ucfirst($documentType) . 'Date';

            // Prüfen ob Nummer vorhanden ist (sollte durch Event-Listener gesetzt sein)
            if (method_exists($orderItem, $getterNumber)) {
                $number = $orderItem->$getterNumber();

                // Ohne Nummer kein PDF erstellen
                if (empty($number)) {
                    // Fallback: Verwende Order-Nummer mit Suffix
                    if ($documentType === 'invoice' && $orderItem->getOrderNumber()) {
                        $orderItem->setInvoiceNumber($orderItem->getOrderNumber() . '-INV');
                        $hasChanges = true;
                    }
                    continue;
                }
            }

            // Datum setzen falls nicht vorhanden
            if (method_exists($orderItem, $getterDate) && !$orderItem->$getterDate()) {
                if (method_exists($orderItem, $setterDate)) {
                    $orderItem->$setterDate(new DateTime());
                    $hasChanges = true;
                }
            }

            try {
                // PDF erzeugen
                $this->pdfService->createPdf($orderItem, $documentType);
            } catch (Exception $e) {
                // Fehler loggen aber Prozess nicht abbrechen
                error_log("PDF generation failed for {$documentType}: " . $e->getMessage());
                continue;
            }
        }

        // Nur speichern wenn Änderungen vorgenommen wurden
        if ($hasChanges) {
            $this->orderItemRepository->update($orderItem);
            $this->persistenceManager->persistAll();
        }
    }
}
