<?php

declare(strict_types=1);

namespace Extcode\CartPdf\EventListener\ProcessOrderCreate;

/*
 * This file is part of the package extcode/cart-pdf.
 *
 * For the full copyright and license information, please read the
 * LICENSE file that was distributed with this source code.
 */

use Extcode\Cart\Domain\Repository\Order\ItemRepository as OrderItemRepository;
use Extcode\Cart\Event\ProcessOrderCreateEvent;
use Extcode\CartPdf\Service\PdfService;
use TYPO3\CMS\Extbase\Persistence\Generic\PersistenceManager;

class DocumentRenderer
{
    public function __construct(
        protected PersistenceManager $persistenceManager,
        protected OrderItemRepository $orderItemRepository,
        protected PdfService $pdfService,
    ) {
    }

    public function __invoke(ProcessOrderCreateEvent $event): void
    {
        $orderItem = $event->getOrderItem();
        $settings = $event->getSettings();

        $generateDocuments = (array)($settings['autoGenerateDocuments'] ?? []);

        if (empty($generateDocuments)) {
            return;
        }

        foreach ($generateDocuments as $documentType => $documentData) {
            if ($documentData) {
                $this->pdfService->createPdf($orderItem, $documentType);
            }
        }

        $this->orderItemRepository->update($orderItem);
        $this->persistenceManager->persistAll();
    }
}
