<?php

declare(strict_types=1);

namespace Extcode\CartPdf\EventListener\Order\Finish;

/*
 * This file is part of the package extcode/cart-pdf.
 *
 * For the full copyright and license information, please read the
 * LICENSE file that was distributed with this source code.
 */

use Extcode\Cart\Domain\Repository\Order\ItemRepository as OrderItemRepository;
use Extcode\Cart\Event\Order\FinishEvent;
use Extcode\CartPdf\Service\DocumentRenderServiceInterface;
use Extcode\CartPdf\Service\FileWriterServiceInterface;
use TYPO3\CMS\Extbase\Persistence\Generic\PersistenceManager;

final readonly class DocumentRenderer
{
    public function __construct(
        private PersistenceManager $persistenceManager,
        private OrderItemRepository $orderItemRepository,
        private DocumentRenderServiceInterface $documentRenderService,
        private FileWriterServiceInterface $fileWriterService,
    ) {}

    public function __invoke(FinishEvent $event): void
    {
        $orderItem = $event->getOrderItem();
        $settings = $event->getSettings();

        $generateDocuments = (array)($settings['autoGenerateDocuments'] ?? []);

        if (empty($generateDocuments)) {
            return;
        }

        foreach ($generateDocuments as $documentType => $documentData) {
            if ($documentData) {
                $this->fileWriterService->writeContentToFile(
                    $orderItem,
                    $documentType,
                    $this->documentRenderService->renderDocument(
                        $orderItem,
                        $documentType
                    )
                );
            }
        }

        $this->orderItemRepository->update($orderItem);
        $this->persistenceManager->persistAll();
    }
}
