<?php

declare(strict_types=1);

namespace Extcode\CartPdf\EventListener\Order\Finish;

/*
 * This file is part of the package extcode/cart-pdf.
 *
 * For the full copyright and license information, please read the
 * LICENSE file that was distributed with this source code.
 */

use Extcode\Cart\Domain\Model\Cart\Cart;
use Extcode\Cart\Domain\Model\Order\Item as OrderItem;
use Extcode\Cart\Domain\Repository\Order\ItemRepository as OrderItemRepository;
use Extcode\Cart\Event\Order\EventInterface;
use Extcode\Cart\Event\Order\NumberGeneratorEvent;
use Extcode\CartPdf\Service\PdfService;
use Psr\EventDispatcher\EventDispatcherInterface;
use Psr\Log\LoggerAwareInterface;
use Psr\Log\LoggerAwareTrait;
use TYPO3\CMS\Extbase\Persistence\Generic\PersistenceManager;

class DocumentRenderer implements LoggerAwareInterface
{
    use LoggerAwareTrait;

    public function __construct(
        protected PersistenceManager $persistenceManager,
        protected OrderItemRepository $orderItemRepository,
        protected PdfService $pdfService,
        protected EventDispatcherInterface $eventDispatcher,
    ) {}

    public function __invoke(EventInterface $event): void
    {
        $orderItem = $event->getOrderItem();
        $settings = $event->getSettings();
        $this->logger->debug('DocumentRenderer', $settings);
        $generateDocuments = (array)($settings['autoGenerateDocuments'] ?? []);

        if (empty($generateDocuments)) {
            return;
        }

        foreach ($generateDocuments as $documentType => $documentData) {
            if ($documentData) {
                $this->createNumberIfMissing($orderItem, $documentType, $settings);
                $this->pdfService->createPdf($orderItem, $documentType);
            }
        }

        $this->orderItemRepository->update($orderItem);
        $this->persistenceManager->persistAll();
    }

    protected function createNumberIfMissing(OrderItem $orderItem, string $pdfType, array $settings)
    {
        $getNumber = 'get' . ucfirst($pdfType) . 'Number';
        if (!$orderItem->$getNumber()) {
            $dummyCart = new Cart([]);
            $createEvent = new NumberGeneratorEvent($dummyCart, $orderItem, $settings);
            $createEvent->setOnlyGenerateNumberOfType([$pdfType]);
            $this->eventDispatcher->dispatch($createEvent);
            $orderItem = $createEvent->getOrderItem();
            $this->orderItemRepository->update($orderItem);
        }
    }
}
